"""Update tasks table structure

Revision ID: update_tasks_table
Revises: add_task_detail_table
Create Date: 2024-03-19 13:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'update_tasks_table'
down_revision = 'add_task_detail_table'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 添加task_type字段
    op.add_column('tasks', sa.Column('task_type', sa.String(length=50), nullable=False, server_default='DOCUMENT_PROCESSING'))
    
    # 添加created_by字段
    op.add_column('tasks', sa.Column('created_by', sa.Integer(), nullable=False, server_default='1'))
    op.create_foreign_key('fk_tasks_created_by', 'tasks', 'users', ['created_by'], ['id'])
    
    # 添加document_id字段
    op.add_column('tasks', sa.Column('document_id', sa.String(length=36), nullable=True))
    op.create_foreign_key('fk_tasks_document_id', 'tasks', 'documents', ['document_id'], ['id'])
    
    # 添加task_metadata字段
    op.add_column('tasks', sa.Column('task_metadata', postgresql.JSONB(), nullable=True))
    
    # 添加steps字段
    op.add_column('tasks', sa.Column('steps', postgresql.JSONB(), nullable=True))
    
    # 修改progress字段类型为float
    op.alter_column('tasks', 'progress',
               existing_type=sa.Integer(),
               type_=sa.Float(),
               existing_nullable=False,
               postgresql_using="progress::float")
    
    # 添加索引
    op.create_index('idx_tasks_document_id', 'tasks', ['document_id'], unique=False)
    op.create_index('idx_tasks_created_by', 'tasks', ['created_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_tasks_created_by', table_name='tasks')
    op.drop_index('idx_tasks_document_id', table_name='tasks')
    op.alter_column('tasks', 'progress',
               existing_type=sa.Float(),
               type_=sa.Integer(),
               existing_nullable=False,
               postgresql_using="progress::integer")
    op.drop_column('tasks', 'steps')
    op.drop_column('tasks', 'task_metadata')
    op.drop_constraint('fk_tasks_document_id', 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'document_id')
    op.drop_constraint('fk_tasks_created_by', 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'created_by')
    op.drop_column('tasks', 'task_type')
    # ### end Alembic commands ### 